POS_DESCRIPTIONS = {
    "ADJ": "Adjektiv",
    "ADP": "Adposition",
    "ADV": "Adverb",
    "AUX": "Hilfsverb",
    "CONJ": "Konjunktion",
    "CCONJ": "Koordinierende Konjunktion",
    "DET": "Determinierer",
    "INTJ": "Interjektion",
    "NOUN": "Substantiv",
    "NUM": "Zahlwort",
    "PART": "Partikel",
    "PRON": "Pronomen",
    "PROPN": "Eigenname",
    "PUNCT": "Interpunktion",
    "SCONJ": "Subordinierende Konjunktion",
    "SYM": "Symbol",
    "VERB": "Verb",
    "X": "Sonstiges / unbekannt"
}

TAG_DESCRIPTIONS = {
    "NN": "Substantiv",
    "NNS": "Substantiv, Plural",
    "NNP": "Eigenname, Singular",
    "NNPS": "Eigennamen, Plural",
    "VB": "Verb",
    "VBD": "Verb, Vergangenheit",
    "VBG": "Verb, Gerundium/Partizip Präsens",
    "VBN": "Verb, Partizip Perfekt",
    "VBP": "Verb, Präsens (nicht 3. Person)",
    "VBZ": "Verb, Präsens 3. Person",
    "JJ": "Adjektiv",
    "JJR": "Adjektiv, Komparativ",
    "JJS": "Adjektiv, Superlativ",
    "RB": "Adverb",
    "RBR": "Adverb, Komparativ",
    "RBS": "Adverb, Superlativ",
    "DT": "Artikel / Determinierer",
    "IN": "Präposition oder subordinierende Konjunktion",
    "PRP": "Personalpronomen",
    "PRP$": "Possessivpronomen",
    "WP": "WH-Pronomen (who, what)",
    "WP$": "Possessives WH-Pronomen (whose)",
    "WRB": "WH-Adverb (where, when, why)",
    "CC": "Koordinierende Konjunktion",
    "CD": "Kardinalzahl",
    "EX": "Expletives Subjekt",
    "FW": "Fremdwort",
    "LS": "Listen-Markierung",
    "MD": "Modalverb",
    "POS": "Possessivsuffix ('s)",
    "RP": "Partikel",
    "SYM": "Symbol",
    "TO": "Infinitivmarker",
    "UH": "Interjektion",
}

NER_LABELS = {
    "PERSON": "Person",
    "NORP": "Nationalität, religiöse oder politische Gruppe",
    "FAC": "Gebäude, Einrichtungen, Infrastruktur",
    "ORG": "Organisation",
    "GPE": "Geopolitische Einheit",
    "LOC": "Geographischer Ort",
    "PRODUCT": "Produkt",
    "EVENT": "Ereignis",
    "WORK_OF_ART": "Kunstwerk",
    "LAW": "Gesetz / Rechtsnorm",
    "LANGUAGE": "Sprache",
    "DATE": "Datum",
    "TIME": "Zeitangabe",
    "PERCENT": "Prozentangabe",
    "MONEY": "Geldbetrag",
    "QUANTITY": "Menge",
    "ORDINAL": "Ordinalzahl",
    "CARDINAL": "Kardinalzahl"
}

DEP_DESCRIPTIONS = {
    "ROOT": "Hauptverb",
    "nsubj": "Nominales Subjekt",
    "nsubjpass": "Subjekt im Passivsatz",
    "csubj": "Satz als Subjekt",
    "csubjpass": "Satz als Subjekt im Passiv",
    "obj": "Objekt",
    "dobj": "Direktes Objekt",
    "iobj": "Indirektes Objekt",
    "pobj": "Präpositionalobjekt",
    "attr": "Attribut",
    "oprd": "Objektsprädikativ",
    "amod": "Adjektivattribut",
    "advmod": "Adverbiale Bestimmung",
    "npadvmod": "Nominale adverbiale Bestimmung",
    "quantmod": "Quantifizierende Bestimmung",
    "det": "Artikel oder Determinierer",
    "predet": "Vorangestellter Determinierer",
    "poss": "Possessivbestimmung",
    "possessive": "Possessivmarker",
    "compound": "Teil eines zusammengesetzten Begriffs",
    "prt": "Verbpartikel",
    "case": "Kasusmarker oder Präposition",
    "prep": "Präpositionale Beziehung",
    "agent": "Handelnder im Passivsatz",
    "acl": "Attributiver Nebensatz",
    "relcl": "Relativsatz",
    "advcl": "Adverbialer Nebensatz",
    "xcomp": "Offene Satzergänzung ohne eigenes Subjekt",
    "ccomp": "Satzergänzung mit eigenem Subjekt",
    "aux": "Hilfsverb",
    "auxpass": "Hilfsverb im Passiv",
    "cop": "Kopulaverb",
    "mark": "Einleitendes Wort eines Nebensatzes",
    "expl": "Expletives Subjekt",
    "cc": "Koordinierende Konjunktion",
    "conj": "Durch Konjunktion verbundenes Element",
    "preconj": "Vorangestellte Konjunktion",
    "punct": "Satzzeichen",
    "appos": "Apposition (erläuternder Zusatz)",
    "nmod": "Nominale Ergänzung",
    "obl": "Adverbiale Ergänzung",
    "parataxis": "Nebenordnung von Satzteilen",
    "dep": "Nicht genauer spezifizierte Abhängigkeit",
    "intj": "Interjektion",
    "discourse": "Diskursmarker",
    "vocative": "Anrede",
    "meta": "Metasprachliches Element",
    "reparandum": "Korrigierter Versprecher oder Fehler",
    "list": "Listenelement",
    "orphan": "Verwaister Satzteil",
    "goeswith": "Zusammengehöriges Wortfragment",
    "fixed": "Feste Wortverbindung",
    "flat": "Flache mehrteilige Benennung",
    "neg": "Negation",
    "number": "Zahlenmodifikator",
    "npmod": "Nominale Modifikation"
}
